# Generated by Django 5.0.3 on 2024-04-22 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hello',
        ),
    ]
