# Generated by Django 5.0.3 on 2024-04-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_logindata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindata',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
